### ISSUE TITLE
Gemfile needs Rake dependency

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/activerecord-associations-intro#11] opened 2016-03-16 15:22 UTC
so can you please tell me why in this project there is no rake dependency declared?  Is the intention of the lab for the student to put it in there?
otherwise it throws an error obviously when trying to run rake tasks like migrations
the error comes from the environment configuration file since it's requiring 'rake' but the lab doesn't have that as a dependency in the Gemfile
of course it's not a problem for me but if that's an intentional thing to correct for the student to learn it should be duly noted.

**Comment by PeterBell** [comment] 2016-03-16 15:38
Hey @genericlady thanks so much for raising the issue - much appreciated! 

> so can you please tell me why in this project there is no rake dependency declared? 

Just trying to clarify what you mean by this. When I look in the config/environment.rb:5 I see `require 'rake'`

What exactly are you trying to do and exactly what error are you getting when you try to do it? When you `gem list` do you have rake as one of your default gems? Just let me know!

**Comment by genericlady** [comment] 2016-03-16 16:22
yes rake is in my list of installed gems.  It still needs to be declared as a `gem 'rake'` in the Gemfile.  When I comment it out from the Gemfile and run bundle the error will reproduce.

The reason we use a Gemfile is to firewall the state of the project from other dependencies that may cause conflict.  So when you run bundle whats actually happening is it's creating Gemfile.lock which locks in your projects dependency's.

But maybe it's something i'm doing wrong.  Maybe it's something in my gem settings with rvm.  i dunno.

**Comment by PeterBell** [comment] 2016-03-16 18:02
Hey @genericlady thanks for raising this. This is generally a source of contention in the ruby world. Some devs always include rake in the Gemfile, some don't. I'm just checking in with the team as to what the "flatiron way" is for this and I'll let you know whether we're casual about rake or believe it should always be included. If we do, I'll submit a PR to fix this and reference your issue. Thanks for raising the quedtion - much appreciated!

**Comment by PeterBell** [comment] 2016-03-16 18:28
Hi @genericlady - couple of things. What version of ruby are you using - I believe 2.x added rake as a default gem. Also I believe it's a dependency of Rails, so I'd expect you to have rake without having to add it to the gemfile. What specific error do you get when you run rake and what version of ruby are you running?

**Comment by genericlady** [comment] 2016-03-17 13:56
Tell me where do you see the rails gem being required ;)

**Comment by genericlady** [comment] 2016-03-17 13:56
Not only that this isn't even a rails project.  We're only using a library of ActiveRecord.

**Comment by genericlady** [comment] 2016-03-17 13:59
Like I said a Gemfile firewalls the state of your projects dependencies.  This is a language agnostic concept.  One way of firewalling the state of a program is through dependencies by calling them into projects explicitly rather then sharing some global pool of dependencies.

**Comment by PeterBell** [comment] 2016-03-17 14:02
Hi @genericlady just confirmed. Ruby 2.0 does have rake as a default gem, so it looks like it's not required in the gemfile:

"(Ruby ships with some gems by default, bigdecimal, io-console, json, minitest, psych, rake, rdoc, test-unit for ruby 2.0.0)."

From http://guides.rubygems.org/rubygems-basics/

So I'm going to close the issue

**Closed by PeterBell** 2016-03-17 14:02 UTC

**Comment by genericlady** [comment] 2016-03-17 14:13
I cloned the repo and am not getting the error from yesterday.  I don't remember why it was happening.  Next time I post an issue I'll copy and paste the error.  Sorry to of wasted your time.

**Comment by PeterBell** [comment] 2016-03-17 14:16
Hi @genericlady no problems at all - appreciate you posting the issue. 

In future, something that really helps is a set of steps and a complete dump of a specific error message, otherwise replicating the error can be hard which usually means the issue goes further down the pile :(
